manifest:
  remotes:
    - name: clicketysplit
      url-base: https://github.com/ClicketySplit
  projects:
    - name: zmk
      remote: clicketysplit
      revision: pepito-v1.13
      import: app/west.yml
  self:
    path: config
